sudo: required
services:
  - docker
before_install:
  - docker build -t danielpatrickgraham/react-test -f ./client/Dockerfile.dev ./client

script:
  #- docker run dpgraham/react-test npm test -- --coverage
  - docker run -e CI=true danielpatrickgraham/react-test npm test

after_success:
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password
  - docker build -t danielpatrickgraham/multi-client ./client
  - docker build -t danielpatrickgraham/multi-nginx ./nginx
  - docker build -t danielpatrickgraham/multi-server ./server
  - docker build -t danielpatrickgraham/multi-worker ./worker
  # Take those images and push them to docker hub
  - docker push danielpatrickgraham/multi-client
  - docker push danielpatrickgraham/multi-nginx
  - docker push danielpatrickgraham/multi-server
  - docker push danielpatrickgraham/multi-worker